# Generated by Django 5.1.6 on 2025-02-27 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Storage', '0005_products_image_products_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(null=True, upload_to='media/products/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='media/products/previews/'),
        ),
    ]
